### ISSUE TITLE
Any integration with using Bower?

### ISSUE THREAD

**Issue by mpochron** [webmandesign/jquery.hoverdir#1]
as title?

**Comment by webmandesign** [comment]
Hi,

I might consider this, but please note that this is just a modified version of https://github.com/codrops/DirectionAwareHoverEffect

Regards,

Oliver

**Comment by webmandesign** [comment]
Hi,

Sorry for such a long delay and not informing you. This should work with Bower now as I've introduced the `bower.json` file.

Regards,

Oliver
