### ISSUE TITLE
Hover delay

### ISSUE THREAD

**Issue by dimensi** [webmandesign/jquery.hoverdir#2]
Hi! You're modification save me. My javascript skill low and english too, but how i can add hoverDelay option from original to your modification?

**Comment by webmandesign** [comment]
Hi,

I'm sorry but this modification does not do any animation, so no delay would work, really. It was created only to do the thing applying a CSS classes on the hovered elements.

So, if you want to delay the hover animation, use an `animation-delay` property for that. https://developer.mozilla.org/en-US/docs/Web/CSS/animation-delay

Regards,

Oliver

**Comment by dimensi** [comment]
I used it, but I could not get the expected. hoverDelay it's something other, it's delay add class for new item.

**Comment by webmandesign** [comment]
Hi,

Sorry, this will not be implemented as like I've said, I've intended the whole modification to port the animation into CSS. Not sure what you aim to do, but I have tried it quickly on https://themedemos.webmandesign.eu/qtron/ and `animation-delay` works perfectly fine for me.

Regards,

Oliver
